:product-agreement:repository:impl -.-> :androidApp
:product-agreement:viewmodel -.-> :androidApp
:product-agreement:android-ui -.-> :androidApp
:product-agreement:repository:interface --> :product-agreement:viewmodel
:product-agreement:repository:interface --> :product-agreement:repository:impl
:product-agreement:domain-model --> :product-agreement:repository:interface
:product-agreement:service --> :product-agreement:repository:impl
:product-agreement:ui-model --> :product-agreement:android-ui
:product-agreement:ui-model --> :product-agreement:viewmodel
:usage:viewmodel -.-> :androidApp
:usage:repository:interface --> :usage:viewmodel
:usage:ui-model --> :usage:viewmodel
:usage:domain-model --> :usage:repository:interface
:usage:repository:interface --> :usage:repository:impl
:usage:repository:impl -.-> :androidApp
:usage:ui-model --> :usage:android-ui
:usage:android-ui -.-> :androidApp
:some-internal-module -.-> :usage:viewmodel
:some-internal-module -.-> :product-agreement:viewmodel
:base:domain-model --> :some-internal-module